### ISSUE TITLE
Deprecated warning in multiplot

### ISSUE THREAD

**Issue by VictorHartman** [jaredlander/coefplot#25]
I am consistently getting the following warning when using multiplot:

```It is deprecated to specify `guide = FALSE` to remove a guide. Please use `guide = "none"` instead. ```

I use the option, by = 'model'

Is this a problem?

Could possible be edited in this line?

https://github.com/jaredlander/coefplot/blob/0077fef6e4fba92981c2c8b9f7b5380c429c7e6a/R/multiplot.r#L217

**Comment by jaredlander** [comment]
This is due to `{ggplot2}` changing it's arguments. You don't have to worry, your results are still correct, you just get that pesky warning. I've been meaning to make a change so that goes away, so thanks for the impetus to actually do that.

Once the change is made and you update `{coefplot}` you won't have to change your code at all.

**Comment by jaredlander** [comment]
Reopening since this needs to be fixed anyway
